Filtering terms in model fix
ga4gh-beacon/beacon-v2 pull request #161
Opened 2024-08-21 19:29 UTC by mbaudis

The previous filteringTerms.yaml/json endpoint definitions were odd:
 - either defined as empty lists (well, okish)
- or having some random values

This PR redefines filteringTerms endpoints as containing a list of

https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/sections/beaconFilteringTermsResults.json#/definitions/FilteringTerm

items. Should be non-breaking.

Thanks to @gsfk for repeatedly voicing concerns about filteringTerms in general ...

2024-08-21 21:28 UTC, gsfk commented
Are these files used anywhere? Is there a compelling reason to keep them?

2024-08-22 07:59 UTC, mbaudis commented
> Are these files used anywhere? Is there a compelling reason to keep them?

@gsfk They represent the endpoints for the entity specific filteringTerms results but are basically stand-ins for resource specific solutions. One could argue that they are defined in openAPI endpoints - but we actually want to transition away from those & need some place to indicate that something like these exists.

That being said, I do not think that the files/definitions are used directly (one of the reasons nobody has cared about their content...).

2024-09-12 11:27 UTC, costero-e requested changes
First of all, I defined a new setting for `schema-urgent-fixes` branch which is to require that all branches must be updated with last commits to `schema-urgent-fixes`, because I was seeing a lot of changes related to undo commits that were already merged to this branch that address and fix things, so this was dangerous as `schema-urgent-fixes` is being used a lot now and will serve later to have a lot of things addressed in a PR to main/develop.
On the other hand, now that I clearly see what was this PR about, I see that the `$ref` in `items` for the src files point to the `beaconFilteringTermsResults.json` file and should be addressed by pointing to the `.yaml` file, which is `https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/src/responses/sections/beaconFilteringTermsResults.yaml`.

2024-12-12 16:06 UTC, costero-e commented
This has been merged in #161

2024-12-12 16:06 UTC, closed without merging